version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://<EC2_IP>:3306/home_services_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "80:80"
  
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: home_services_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
