version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
