name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Ensure docker-compose is executable
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          sudo chmod +x /usr/local/bin/docker-compose
          EOF

      - name: Copy project to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "mkdir -p ~/app"
          scp -o StrictHostKeyChecking=no -r ./backend ubuntu@${{ secrets.EC2_HOST }}:~/app
          scp -o StrictHostKeyChecking=no -r ./frontend ubuntu@${{ secrets.EC2_HOST }}:~/app
          scp -o StrictHostKeyChecking=no ./docker-compose.yml ubuntu@${{ secrets.EC2_HOST }}:~/app

      - name: Deploy Docker containers
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/app
          docker-compose down
          docker-compose build
          docker-compose up -d
          EOF
