name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0  # use the latest stable version
        with:
            ssh-private-key: ${{ secrets.EC2_SSH_KEY }}


      - name: Copy project to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@<EC2_IP> "mkdir -p ~/app"
          scp -o StrictHostKeyChecking=no -r ./backend ec2-user@<EC2_IP>:~/app
          scp -o StrictHostKeyChecking=no -r ./frontend ec2-user@<EC2_IP>:~/app
          scp -o StrictHostKeyChecking=no ./docker-compose.yml ec2-user@<EC2_IP>:~/app

      - name: Deploy Docker containers
        run: |
          ssh ec2-user@<EC2_IP> "
          cd ~/app
          docker compose down
          docker compose build
          docker compose up -d
          "


          